[package]
name = "libium"
version = "1.22.1"
edition = "2021"
authors = [
    "Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>",
    "Daniel Hauck (SolidTux)",
]
description = "Multi-source backend for managing Minecraft mods and modpacks from Modrinth, CurseForge, and Github Releases"
repository = "https://github.com/gorilla-devs/libium"
readme = "README.md"
license = "MPL-2.0"
keywords = [
    "minecraft",
    "mod-manager",
    "modrinth",
    "curseforge",
    "github-releases",
]

[features]
gui = ["rfd"]

[dependencies]
rfd = { version = "0.10", default-features = false, optional = true, features = [
    "xdg-portal",
] }
octocrab = { version = "0.18", default-features = false, features = ["rustls"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
tokio = { version = "1.23", default-features = false, features = ["fs"] }
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
url = { version = "2.3", features = ["serde"] }
serde_json = "1.0"
dialoguer = "0.10"
once_cell = "1.17"
thiserror = "1.0"
ferinth = "2.7"
furse = "1.5"
home = "0.5"
