[package]
name = "libium"
version = "1.0.0"
edition = "2021"
authors = ["theRookieCoder <ileshkt@gmail.com>"]
description = "Libium is the backend of Ferium. It helps manage Minecraft mods from Modrinth, CurseForge, and Github Releases"
repository = "https://github.com/theRookieCoder/libium"
readme = "README.md"
license = "MPL-2.0"
keywords = [
	"minecraft",
	"mod-manager",
	"modrinth",
	"curseforge",
	"github-releases"
]

[features]
gui = ["rfd"]

[dependencies]
reqwest = { version = "0", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "3", features = ["derive"] }
tokio = { version = "1", features = ["fs"] }
lazy_static = "1"
serde_json = "1"
semver = "1"
home = "0"
rfd = { version = "0", optional = true }
dialoguer = "0"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
