[package]
name = "libium"
version = "1.21.1"
edition = "2021"
authors = [
    "Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>",
    "Daniel Hauck (SolidTux)",
]
description = "Multi-source backend for managing Minecraft mods and modpacks from Modrinth, CurseForge, and Github Releases"
repository = "https://github.com/gorilla-devs/libium"
readme = "README.md"
license = "MPL-2.0"
keywords = [
    "minecraft",
    "mod-manager",
    "modrinth",
    "curseforge",
    "github-releases",
]

[features]
gui = ["rfd"]

[dependencies]
rfd = { version = "~0.10.0", default-features = false, optional = true, features = [
    "xdg-portal",
] }
reqwest = { version = "~0.11.12", default-features = false, features = [
    "rustls-tls",
    "json",
] }
octocrab = { version = "~0.17.0", default-features = false, features = [
    "rustls",
] }
tokio = { version = "~1.21.2", default-features = false, features = ["fs"] }
serde = { version = "~1.0.147", features = ["derive"] }
clap = { version = "~4.0.23", features = ["derive"] }
url = { version = "~2.2.2", features = ["serde"] }
lazy_static = "~1.4.0"
serde_json = "~1.0.87"
dialoguer = "~0.10.2"
thiserror = "~1.0.37"
ferinth = "~2.7.1"
bytes = "~1.1.0"
furse = "~1.5.6"
home = "~0.5.4"
zip = "~0.6.3"
