[package]
name = "libium"
version = "1.23.2"
edition = "2021"
authors = [
    "Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>",
    "Daniel Hauck (SolidTux)",
]
description = "Multi-source backend for managing Minecraft mods and modpacks from Modrinth, CurseForge, and Github Releases"
repository = "https://github.com/gorilla-devs/libium"
readme = "README.md"
license = "MPL-2.0"
keywords = [
    "minecraft",
    "mod-manager",
    "modrinth",
    "curseforge",
    "github-releases",
]

[features]
gui = ["rfd"]

[dependencies]
rfd = { version = "0.13", default-features = false, optional = true, features = [
    "xdg-portal",
] }
octocrab = { version = "0.33", default-features = false, features = [
    "rustls",
    "rustls-webpki-tokio",
] }
tokio = { version = "1.35", default-features = false, features = ["fs"] }
# Locked due to possibility of breaking changes
async_zip = { version = "=0.0.12", default-features = false, features = [
    "deflate",
] }
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.4", features = ["derive"] }
url = { version = "2.5", features = ["serde"] }
async-recursion = "1.0"
serde_json = "1.0"
dialoguer = "0.11"
once_cell = "1.19"
thiserror = "1.0"
ferinth = "2.10"
furse = "1.5"
home = "0.5"
