[package]
name = "libium"
version = "1.11.1"
edition = "2021"
authors = ["Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>", "Daniel Hauck (SolidTux)"]
description = "Libium is the backend of Ferium. It helps manage Minecraft mods from Modrinth, CurseForge, and Github Releases"
repository = "https://github.com/theRookieCoder/libium"
readme = "README.md"
license = "MPL-2.0"
keywords = [
	"minecraft",
	"mod-manager",
	"modrinth",
	"curseforge",
	"github-releases"
]

[features]
gui = ["rfd"]

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
octocrab = { version = "0.16", default-features = false, features = ["rustls"]}
tokio = { version = "1.18", default-features = false, features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "3.1", features = ["derive"] }
rfd = { version = "0.8", optional = true }
lazy_static = "1.4"
dialoguer = "0.10"
serde_json = "1.0"
thiserror = "1.0"
ferinth = "2.2"
bytes = "1.1"
furse = "1.1"
home = "0.5"
