[package]
name = "libium"
version = "1.9.0"
edition = "2021"
authors = ["Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>", "Daniel Hauck (SolidTux)"]
description = "Libium is the backend of Ferium. It helps manage Minecraft mods from Modrinth, CurseForge, and Github Releases"
repository = "https://github.com/theRookieCoder/libium"
readme = "README.md"
license = "MPL-2.0"
keywords = [
	"minecraft",
	"mod-manager",
	"modrinth",
	"curseforge",
	"github-releases"
]

[features]
gui = ["rfd"]

[dependencies]
reqwest = { version = "0", default-features = false, features = ["rustls-tls", "json"] }
octocrab = { version = "0", default-features = false, features = ["rustls"]}
tokio = { version = "1", default-features = false, features = ["fs"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "3", features = ["derive"] }
rfd = { version = "0", optional = true }
lazy_static = "1"
serde_json = "1"
dialoguer = "0"
thiserror = "1"
ferinth = "2"
bytes = "1"
furse = "1"
home = "0"
